image: debian
before_script:
- cd sources
- apt-get install php7*
- php -v
- git submodule update --init
- php -v
- composer --version
- git --version
- ls -lah
- composer self-update
- composer config --global github-oauth.github.com $GITHUB_TOKEN
- composer install --no-interaction
- php artisan env
- touch database/testing.sqlite
- php artisan migrate --database=testing --env=testing

stages:
- test

test:
  script:
  - vendor/bin/phpunit
  - vendor/bin/phpmd app/ text phpmd.xml
  - vendor/bin/phpcs --standard=psr2 app