image: php:7.1.3

stages:
  - deploy
  - build
  - migrate

build:
  stage: build
  script:
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - heroku run --app $HEROKU_APP_NAME composer update
    - heroku run --app $HEROKU_APP_NAME composer dump-autoload
  only:
    refs:
      - master

deploy:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq git
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
  only:
    refs:
      - master

migrate:
  stage: migrate
  script:
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - heroku run --app $HEROKU_APP_NAME php artisan migrate
  only:
    refs:
      - master
