before_script:
- bash .gitlab-ci.sh

variables:
  MYSQL_DATABASE: project_name
  MYSQL_ROOT_PASSWORD: secret

phpunit:php7.0:mysql5.7:
  image: php:7.0
  services:
  - mysql:5.7
  script:
  - php bin/phpunit --colors
