image: php:7.1.3

pipelines:
  branches:
    master:

    - step:
          name: Deploy
          deployment: test
          script:
          - apt-get update && apt-get install -y git
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD

    - step:
        name: Build & Migrate
        script:
        - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
        - heroku run --app $HEROKU_APP_NAME composer update
        - heroku run --app $HEROKU_APP_NAME composer dump-autoload
        - heroku run --app $HEROKU_APP_NAME php artisan migrate
